helmBinary: helm
missingFileHandler: Error
namespace: {{ requiredEnv "NAMESPACE" }}
helmfiles:
#Actually this is another repo
  - path: "git::https://github.com/Pela2silveira/misc@/helmfile/example/remote-repo/helmfiles/wordpress.yaml"
    selectors:
    - name=wordpress
    values:
    - ../values/wordpress.yaml
